version: '3.1'

services:
  db_dev:
    image: mysql
    container_name: "DevVegitoDB"
    ports:
      - 3307:3306
    env_file:
      - db_dev.env
    restart: on-failure
    volumes:
      - vegitopraiser_data_dev:/var/lib/mysql
  db_scheduler_dev:
    image: mongo
    restart: on-failure
    env_file:
      - db_scheduler_dev.env
    ports:
      - 27018:27017

volumes:
  vegitopraiser_data_dev:
    external: true

networks:
  vegitopraiser_dev:
    driver: brigde