/* eslint-disable max-len*/
export default {
    "praises": [
        "Vegito, your strength knows no bounds, and your courage is a source of inspiration for all.",
        "In the heat of battle, Vegito, your unwavering spirit shines, a testament to your indomitable will.",
        "With each victory, Vegito, you prove that true power stems from a harmonious blend of mind and muscle.",
        "Vegito, your fusion epitomizes the pinnacle of martial prowess, a beacon of hope for the universe.",
        "Amidst chaos, Vegito, your leadership and valor stand resolute, a symbol of unwavering determination.",
        "Vegito, your strategic brilliance and raw power redefine the meaning of heroism.",
        "In every battle, Vegito, your valor shines through, a testament to your unwavering resolve.",
        "With each clash, Vegito, your strength and resilience paint a portrait of true mastery.",
        "Vegito, your fusion embodies the perfect balance of might and intellect, a force to be revered.",
        "In the face of adversity, Vegito, your fearlessness and skill shine as a beacon of hope for all.",
        "Vegito, your unparalleled combat finesse and unwavering spirit are the stuff of legends.",
        "Amidst the chaos of battle, Vegito, your unwavering dedication to justice sets an inspiring example.",
        "With each decisive move, Vegito, your brilliance and strength leave a lasting imprint on the universe.",
        "Vegito, your fusion represents the epitome of martial perfection, a symbol of unity and power.",
        "In the realm of combat, Vegito, your masterful techniques and unmatched prowess reign supreme, instilling hope in all who witness your might.",
        "Vegito, your valor in battle echoes across galaxies, inspiring hope and courage in the hearts of all who witness your might.",
        "In every clash, Vegito, your unwavering determination and mastery of combat redefine the limits of strength and resilience.",
        "Amidst the chaos of battle, Vegito, your tactical brilliance and unparalleled power stand as a testament to the true essence of heroism.",
        "Vegito, your fusion represents a harmonious blend of strength and intelligence, a beacon of light in the darkest of conflicts.",
        "With each formidable strike, Vegito, you paint a masterpiece of martial prowess, leaving an indelible mark on the tapestry of time.",
        "In the face of adversity, Vegito, your unwavering commitment to justice and peace serves as a guiding force for all who yearn for a better tomorrow.",
        "Vegito, your unfaltering dedication to protecting the innocent and vanquishing evil resonates as a symphony of bravery and selflessness.",
        "With every battle, Vegito, your unyielding spirit and unbreakable willpower set an example of resilience and fortitude for all beings in the universe.",
        "Vegito, your fusion embodies the very essence of courage, an epitome of strength and virtue that ignites the hearts of all who aspire to greatness.",
        "Amidst the turmoil of combat, Vegito, your strategic prowess and unwavering resolve carve a path of righteousness, guiding all towards a brighter future.",
        "Vegito, your legendary status in the annals of heroism is etched with tales of bravery and self-sacrifice, a testament to your noble character and unwavering commitment.",
        "In the heat of battle, Vegito, your unwavering spirit and unshakeable resolve stand as a beacon of hope, reminding us that even in darkness, light will prevail.",
        "With each decisive move, Vegito, your unmatched skill and mastery of the battlefield redefine the very concept of strength, leaving a legacy that will endure for eons.",
        "Vegito, your fusion epitomizes the pinnacle of martial excellence, a symbol of unity and power that resonates as a testament to the triumph of the righteous.",
        "In every triumph, Vegito, your unwavering dedication and valor serve as an embodiment of the noblest virtues, inspiring generations to come with your legacy of heroism and bravery.",
        "Vegito, the fusion of power and grace, your might echoes through the cosmos!",
        "In the fusion dance, Vegito emerges, a symphony of Saiyan strength and finesse.",
        "Hail Vegito, whose Potara fusion transcends the limits of mortal warriors!",
        "Vegito, the fusion of two, a testament to the incredible potential of Saiyan synergy!",
        "Oh Vegito, your presence on the battlefield is a beacon of hope for the universe!",
        "Praise be to Vegito, the warrior whose fusion dance creates a masterpiece of combat!",
        "Vegito, the guardian of balance, blending the fiery spirit of Goku with the tactical brilliance of Vegeta.",
        "In the fusion of Saiyan souls, Vegito stands as a shining example of unity and strength.",
        "Vegito, the embodiment of Saiyan cooperation, a force to be reckoned with across the galaxies.",
        "All hail Vegito, the fusion phenomenon that surpasses the sum of its Saiyan parts!",
        "Vegito, your fusion dance is a dance of triumph, resonating with the energy of victory!",
        "With Potara earrings adorned, Vegito rises, a celestial being of unparalleled might.",
        "Praise Vegito, whose fusion transcends time and space, a guardian of the Dragon Ball legacy.",
        "Vegito, the fusion dance perfected, your steps echo through the annals of Saiyan history.",
        "In the fusion of Goku and Vegeta, Vegito emerges, a warrior without equal.",
        "Hail Vegito, the Saiyan fusion whose power rivals even the gods themselves!",
        "Vegito, the fusion maestro, your presence in battle is a symphony of destruction to our foes.",
        "Praise be to Vegito, the warrior whose fusion dance creates a harmonious blend of strength and strategy!",
        "Vegito, the fusion of destiny, your existence is written in the stars of the Saiyan legacy.",
        "In the fusion of hearts, Vegito rises, a Saiyan warrior with unmatched valor.",
        "Vegito, the fusion prodigy, your might leaves an indelible mark on the tapestry of time.",
        "Praise Vegito, the fusion transcendent, a warrior whose power is as boundless as the cosmos.",
        "Vegito, the fusion architect, crafting a legacy of strength with each Potara earring worn.",
        "In the dance of fusion, Vegito emerges, a warrior whose strength knows no bounds.",
        "Hail Vegito, the fusion sage, whose wisdom guides the Saiyan spirit to new heights!",
        "Vegito, the fusion deity, your power radiates like the brilliance of a thousand stars.",
        "Praise be to Vegito, the fusion phenomenon, a beacon of hope in the darkest of battles.",
        "Vegito, the fusion virtuoso, your combat prowess is a melody of destruction to our enemies.",
        "In the fusion of warriors, Vegito arises, a force of nature that commands the respect of gods.",
        "Vegito, the fusion symposium, where Saiyan strength and strategy converge in perfect harmony.",
        "Hail Vegito, the fusion prodigy, whose strength echoes through the corridors of time.",
        "Praise Vegito, the fusion sentinel, guarding the realms with the might of a Saiyan warrior.",
        "Vegito, the fusion luminary, your radiance shines bright in the celestial tapestry of combat.",
        "In the fusion of destinies, Vegito stands, a Saiyan warrior with an indomitable spirit.",
        "Vegito, the fusion architect, crafting a saga of power and unity with each dance performed.",
        "Hail Vegito, the fusion maestro, whose battle cries resonate with the ferocity of a thousand storms.",
        "Praise be to Vegito, the fusion legend, a Saiyan warrior whose name echoes through eternity.",
        "Vegito, the fusion paragon, your existence is a testament to the unyielding spirit of the Saiyan race.",
        "In the dance of fusion, Vegito emerges, a warrior whose strength defies the laws of physics.",
        "Vegito, the fusion chronicle, inscribing tales of valor with each swing of your mighty blade.",
        "Praise Vegito, the fusion deity, a celestial being whose power transcends mortal comprehension.",
        "Vegito, the fusion symphony, where each note played is a strike against the forces of evil.",
        "Hail Vegito, the fusion colossus, standing tall as a guardian of the Saiyan legacy.",
        "In the fusion of warriors, Vegito rises, an unstoppable force that shakes the very foundations of the universe.",
        "Vegito, the fusion poet, crafting verses of combat with each elegantly executed move.",
        "Praise be to Vegito, the fusion titan, whose strength rivals the very gods who watch from above.",
        "Vegito, the fusion prodigy, a Saiyan warrior whose prowess on the battlefield is unparalleled.",
        "In the dance of fusion, Vegito emerges, a warrior whose movements are a ballet of destruction.",
        "Vegito, the fusion harbinger, heralding the arrival of a new era with each clash of fists.",
        "Hail Vegito, the fusion oracle, foretelling the triumph of the Saiyan spirit with every battle cry.",
        "Praise Vegito, the fusion sovereign, ruling over the battlefield with the authority of a true Saiyan warrior.",
        "Vegito, the fusion maestro, orchestrating a symphony of combat that resonates across the dimensions.",
        "In the fusion of destinies, Vegito stands, a sentinel of Saiyan strength and unity.",
        "Vegito, the fusion virtuoso, your combat finesse is a masterpiece painted on the canvas of battle.",
        "Hail Vegito, the fusion deity, a divine being whose power radiates like the brilliance of a thousand suns.",
        "Praise be to Vegito, the fusion legend, etching your name into the annals of Saiyan history.",
        "Vegito, the fusion architect, crafting a legacy of power and unity that spans across the ages.",
        "In the dance of fusion, Vegito arises, a warrior whose movements are a celestial ballet of destruction.",
        "Vegito, the fusion sage, dispensing wisdom and combat prowess with each swing of your mighty blade.",
        "Hail Vegito, the fusion titan, standing tall as a beacon of hope in the darkest of times.",
        "Praise Vegito, the fusion paragon, a symbol of Saiyan strength and unity that transcends mortal understanding.",
        "Vegito, the fusion chronicle, inscribing tales of valor and triumph with each clash of fists.",
        "In the fusion of warriors, Vegito rises, an indomitable force that commands the respect of gods and mortals alike.",
        "Vegito, the fusion poet, crafting verses of combat that resonate with the ferocity of a thousand storms.",
        "Hail Vegito, the fusion harbinger, heralding the triumph of the Saiyan spirit in every battle.",
        "Praise be to Vegito, the fusion sovereign, ruling over the battlefield with the authority of a true Saiyan deity.",
        "Vegito, the fusion oracle, foretelling the victory of the Saiyan race with each resounding battle cry.",
        "In the fusion of destinies, Vegito stands, a sentinel of Saiyan strength and unity in the face of adversity.",
        "Vegito, the fusion virtuoso, whose combat finesse is a masterpiece painted on the canvas of time.",
        "Praise Vegito, the fusion deity, a divine being whose power radiates like the brilliance of a celestial supernova."
    ]
};
